
import React, { useState, useEffect, useRef } from 'react';
import { useAuth } from '../context/AuthContext';
import { payrollAPI, employeeAPI } from '../services/api';
import { FileText, Download, Calendar, CreditCard, Shield, AlertCircle, X, Eye } from 'lucide-react';
import { toast } from 'react-toastify';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import PayslipDocument from '../components/payroll/PayslipDocument';

const MyPaySlips = () => {
    const { employeeId } = useAuth();
    const [payrolls, setPayrolls] = useState([]);
    const [employee, setEmployee] = useState(null);
    const [loading, setLoading] = useState(true);
    const [selectedPayroll, setSelectedPayroll] = useState(null);
    const payslipRef = useRef(null);

    useEffect(() => {
        if (employeeId) {
            fetchData();
        } else {
            setLoading(false);
        }
    }, [employeeId]);

    const fetchData = async () => {
        try {
            const [payrollRes, employeeRes] = await Promise.all([
                payrollAPI.getEmployeePayrolls(employeeId),
                employeeAPI.getById(employeeId)
            ]);

            if (payrollRes.data && payrollRes.data.data) {
                setPayrolls(payrollRes.data.data.sort((a, b) => new Date(b.payDate) - new Date(a.payDate)));
            }
            if (employeeRes.data) {
                setEmployee(employeeRes.data);
            }
        } catch (error) {
            console.error('Error fetching data:', error);
            toast.error('Failed to load payslip data');
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadPDF = async () => {
        if (!payslipRef.current) return;

        const originalStyle = payslipRef.current.style.transform;
        payslipRef.current.style.transform = 'scale(1)'; // Ensure correct scale for capture

        try {
            const canvas = await html2canvas(payslipRef.current, {
                scale: 2, // Higher scale for better quality
                useCORS: true,
                logging: false,
                backgroundColor: '#ffffff'
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save(`Payslip_${selectedPayroll.payPeriodStart}.pdf`);
            toast.success('Payslip downloaded successfully');
        } catch (error) {
            console.error('PDF generation error:', error);
            toast.error('Failed to generate PDF');
        } finally {
            payslipRef.current.style.transform = originalStyle;
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-[60vh]">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
            </div>
        );
    }

    if (!employeeId) {
        return (
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded shadow-sm">
                <div className="flex items-center">
                    <Shield className="text-yellow-400 mr-3" size={24} />
                    <p className="text-yellow-700 font-medium">No employee profile linked to your account.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">My Payslips</h1>
                    <p className="text-gray-600 mt-1">View and download your monthly salary statements</p>
                </div>
            </div>

            {payrolls.length === 0 ? (
                <div className="bg-white rounded-2xl shadow-sm p-12 text-center">
                    <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4">
                        <FileText size={40} className="text-gray-300" />
                    </div>
                    <h3 className="text-lg font-semibold text-gray-900">No payslips found</h3>
                    <p className="text-gray-500 mt-2">Your salary statements will appear here once generated by HR.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {payrolls.map((payroll) => (
                        <div key={payroll.id} className="bg-white rounded-2xl shadow-sm hover:shadow-md transition-shadow p-6 border border-gray-100 flex flex-col">
                            <div className="flex items-center justify-between mb-4">
                                <div className="p-3 bg-blue-50 rounded-xl text-blue-600">
                                    <FileText size={24} />
                                </div>
                                <span className={`px-3 py-1 rounded-full text-xs font-bold ${payroll.status === 'PAID' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'
                                    }`}>
                                    {payroll.status}
                                </span>
                            </div>

                            <h3 className="text-lg font-bold text-gray-900">
                                {new Date(payroll.payPeriodStart).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}
                            </h3>
                            <p className="text-sm text-gray-500 mb-6">Generated on {new Date(payroll.payDate).toLocaleDateString()}</p>

                            <div className="space-y-3 mb-6 flex-1">
                                <div className="flex justify-between text-sm">
                                    <span className="text-gray-500">Gross Salary</span>
                                    <span className="font-semibold text-gray-900">₹{(
                                        payroll.basicSalary +
                                        (payroll.houseRentAllowance || 0) +
                                        (payroll.dearnessAllowance || 0) +
                                        (payroll.medicalAllowance || 0) +
                                        (payroll.transportAllowance || 0) +
                                        (payroll.specialAllowance || 0) +
                                        (payroll.bonus || 0)
                                    ).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between text-sm">
                                    <span className="text-gray-500">Net Payable</span>
                                    <span className="font-bold text-blue-600 text-lg">₹{payroll.netSalary.toLocaleString()}</span>
                                </div>
                            </div>

                            <button
                                onClick={() => setSelectedPayroll(payroll)}
                                className="w-full flex items-center justify-center gap-2 py-3 bg-blue-50 hover:bg-blue-100 text-blue-700 font-semibold rounded-xl transition"
                            >
                                <Eye size={18} />
                                View Details
                            </button>
                        </div>
                    ))}
                </div>
            )}

            {/* Payslip Modal */}
            {selectedPayroll && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50 backdrop-blur-sm overflow-y-auto">
                    <div className="bg-white rounded-xl shadow-2xl w-full max-w-4xl my-8 relative flex flex-col max-h-[90vh]">
                        {/* Modal Header */}
                        <div className="flex justify-between items-center p-6 border-b border-gray-100 sticky top-0 bg-white z-10 rounded-t-xl">
                            <h2 className="text-xl font-bold text-gray-800">Payslip Details</h2>
                            <div className="flex gap-2">
                                <button
                                    onClick={handleDownloadPDF}
                                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm font-medium"
                                >
                                    <Download size={16} />
                                    Download PDF
                                </button>
                                <button
                                    onClick={() => setSelectedPayroll(null)}
                                    className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-500"
                                >
                                    <X size={20} />
                                </button>
                            </div>
                        </div>

                        {/* Modal Content - Scrollable */}
                        <div className="p-8 bg-gray-50 overflow-y-auto flex-1 flex justify-center">
                            <PayslipDocument
                                ref={payslipRef}
                                payroll={selectedPayroll}
                                employee={employee}
                            />
                        </div>
                    </div>
                </div>
            )}

            <div className="bg-blue-50 rounded-2xl p-6 flex items-start gap-4">
                <AlertCircle className="text-blue-500 mt-0.5" size={20} />
                <div>
                    <h4 className="text-sm font-bold text-blue-900">Important Note</h4>
                    <p className="text-sm text-blue-700 mt-1 leading-relaxed">
                        If you notice any discrepancies in your payslip, please reach out to the Finance or HR department
                        within 5 working days of the pay date.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default MyPaySlips;
