import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { payrollAPI } from '../services/api';
import { FileText, Download, Calendar, CreditCard, Shield, AlertCircle } from 'lucide-react';
import { toast } from 'react-toastify';

const MyPaySlips = () => {
    const { employeeId } = useAuth();
    const [payrolls, setPayrolls] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (employeeId) {
            fetchPayrolls();
        } else {
            setLoading(false);
        }
    }, [employeeId]);

    const fetchPayrolls = async () => {
        try {
            const response = await payrollAPI.getEmployeePayrolls(employeeId);
            setPayrolls(response.data.sort((a, b) => new Date(b.payDate) - new Date(a.payDate)));
        } catch (error) {
            console.error('Error fetching payrolls:', error);
            toast.error('Failed to load payslips');
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center h-[60vh]">
                <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-blue-500"></div>
            </div>
        );
    }

    if (!employeeId) {
        return (
            <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded shadow-sm">
                <div className="flex items-center">
                    <Shield className="text-yellow-400 mr-3" size={24} />
                    <p className="text-yellow-700 font-medium">No employee profile linked to your account.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900">My Payslips</h1>
                    <p className="text-gray-600 mt-1">View and download your monthly salary statements</p>
                </div>
            </div>

            {payrolls.length === 0 ? (
                <div className="bg-white rounded-2xl shadow-sm p-12 text-center">
                    <div className="w-20 h-20 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4">
                        <FileText size={40} className="text-gray-300" />
                    </div>
                    <h3 className="text-lg font-semibold text-gray-900">No payslips found</h3>
                    <p className="text-gray-500 mt-2">Your salary statements will appear here once generated by HR.</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {payrolls.map((payroll) => (
                        <div key={payroll.id} className="bg-white rounded-2xl shadow-sm hover:shadow-md transition-shadow p-6 border border-gray-100 flex flex-col">
                            <div className="flex items-center justify-between mb-4">
                                <div className="p-3 bg-blue-50 rounded-xl text-blue-600">
                                    <FileText size={24} />
                                </div>
                                <span className={`px-3 py-1 rounded-full text-xs font-bold ${payroll.status === 'PAID' ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'
                                    }`}>
                                    {payroll.status}
                                </span>
                            </div>

                            <h3 className="text-lg font-bold text-gray-900">
                                {new Date(payroll.payPeriodStart).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}
                            </h3>
                            <p className="text-sm text-gray-500 mb-6">Generated on {new Date(payroll.payDate).toLocaleDateString()}</p>

                            <div className="space-y-3 mb-6 flex-1">
                                <div className="flex justify-between text-sm">
                                    <span className="text-gray-500">Gross Salary</span>
                                    <span className="font-semibold text-gray-900">₹{(payroll.basicSalary + payroll.allowances + payroll.bonus).toLocaleString()}</span>
                                </div>
                                <div className="flex justify-between text-sm">
                                    <span className="text-gray-500">Deductions</span>
                                    <span className="font-semibold text-red-600">-₹{payroll.deductions.toLocaleString()}</span>
                                </div>
                                <div className="border-t border-dashed border-gray-200 pt-3 flex justify-between">
                                    <span className="font-bold text-gray-900">Net Payable</span>
                                    <span className="font-bold text-blue-600 text-lg">₹{payroll.netSalary.toLocaleString()}</span>
                                </div>
                            </div>

                            <button
                                onClick={() => toast.info('Download feature coming soon!')}
                                className="w-full flex items-center justify-center gap-2 py-3 bg-gray-50 hover:bg-gray-100 text-gray-700 font-semibold rounded-xl transition"
                            >
                                <Download size={18} />
                                Download PDF
                            </button>
                        </div>
                    ))}
                </div>
            )}

            <div className="bg-blue-50 rounded-2xl p-6 flex items-start gap-4">
                <AlertCircle className="text-blue-500 mt-0.5" size={20} />
                <div>
                    <h4 className="text-sm font-bold text-blue-900">Important Note</h4>
                    <p className="text-sm text-blue-700 mt-1 leading-relaxed">
                        If you notice any discrepancies in your payslip, please reach out to the Finance or HR department
                        within 5 working days of the pay date.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default MyPaySlips;
